apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nest-backend      
  namespace: argocd       
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default    
  source:
    repoURL: git@github.com:richardguedesrib/tharseo_backend_v2.git   
    targetRevision: main   
    path: argocd           
  project: default         
