apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tharseo-backend-v2-nestjs
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: git@github.com:richardguedesrib/tharseo_backend_v2.git
    targetRevision: main
    path: argocd
  project: default
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true  
