describe("Navigation test", () => {
  it("penultimo teste", () => {
    cy.visit("https://tharseocripto.web.app/signin");
    cy.get("#email").type("alberto.ribeiro.oliveirahotmail.com");
    cy.get(".gap-6 > .inline-flex").click();
    cy.wait(2000);
    cy.get("#email").clear().type("alberto.ribeiro.oliveira@hotmail.com");
    cy.get(".gap-6 > .inline-flex").click();
    cy.get("#password").type("fatec12345");
    cy.get(".gap-6 > .inline-flex").click();
    cy.wait(2000);
    cy.get("#password").clear().type("Fatec12345");
    cy.get(".gap-6 > .inline-flex").click();
    cy.get('.group > .min-w-0 > :nth-child(5) > .peer\\/menu-button').click();
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(1)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(2)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(3)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(4)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(6)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(7)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(8)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(9)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(10)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(1)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(2)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(3)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(4)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(6)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(7)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(8)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(9)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rg\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rh\\: > :nth-child(10)').click();
    cy.wait(2000);
  });
});