describe("Navigation test", () => {
  it("O processo de login ao fim deve ser feito com sucesso, testaremos a entrada de dados com um e-mail errado, porém a senha correta e vice versa, o processo de login só poderá ser feito com sucesso com login e senha validos simultâneos", () => {
    cy.visit("https://tharseocripto.web.app/signin");
    cy.get("#email").type("alberto.ribeiro.oliveirahotmail.com");
    cy.get(".gap-6 > .inline-flex").click();
    cy.wait(2000);
    cy.get("#email").clear().type("alberto.ribeiro.oliveira@hotmail.com");
    cy.get(".gap-6 > .inline-flex").click();
    cy.get("#password").type("fatec12345");
    cy.get(".gap-6 > .inline-flex").click();
    cy.wait(2000);
    cy.get("#password").clear().type("Fatec12345");
    cy.get(".gap-6 > .inline-flex").click();
    cy.get('.group > .min-w-0 > :nth-child(3) > .peer\\/menu-button').click();
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(1)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(2)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(3)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(4)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(5)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(1)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(2)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(3)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(4)').click();
    cy.wait(2000);
    cy.get('#radix-\\:rc\\:').click();
    cy.wait(1000);
    cy.get('#radix-\\:rd\\: > :nth-child(5)').click();
    cy.get('.relative > .inline-flex').click();
    cy.get('#name').type('Teste');
    cy.get('#description').type('Teste do cypress');
    cy.get('#isActive').click();
    cy.get('#quantityGrids').type('2');
    cy.get('#valueOrder').type('25');
    cy.get('#profitTarget').type('100');
    cy.get('#variableOrder').type('13');
    cy.get('.space-y-4 > .justify-center').click();
  });
});