apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
  labels:
    app: nest-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: ghcr.io/richardguedesrib/tharseo_backend_v2:nest-latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
