apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-backend
  labels:
    app: nest-backend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nest-backend
  template:
    metadata:
      labels:
        app: nest-backend
    spec:
      containers:
        - name: nest-backend
          image: ghcr.io/richardguedesrib/tharseo-backend-v2:nest-ce18666
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: nestjs-secret
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nestjs-secret
                  key: SECRET_KEY
            - name: BINANCE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: nestjs-secret
                  key: BINANCE_API_KEY
            - name: BINANCE_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: nestjs-secret
                  key: BINANCE_API_SECRET
            - name: BINANCE_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: nestjs-secret
                  key: BINANCE_BASE_URL
