name: Build and Deploy to GHCR + ArgoCD Sync

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=nest-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/richardguedesrib/tharseo-backend-v2:${{ env.IMAGE_TAG }}

      - name: Update deployment.yaml with new image tag
        run: |
          sed -i "s|ghcr.io/richardguedesrib/tharseo-backend-v2:.*|ghcr.io/richardguedesrib/tharseo-backend-v2:${{ env.IMAGE_TAG }}|" argocd/deployment.yaml

      - name: Commit and push updated manifest
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add argocd/deployment.yaml
          git commit -m "chore: update image tag to ${{ env.IMAGE_TAG }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
